### ISSUE TITLE
settle on a forwards-compatible exit format

### ISSUE THREAD

**Issue by geoknee** [statechannels/exit-format#30]
**[NEW] What is this issue for**
So far we have anticipated `WithdrawHelpers` (they use `callTo` and `data`) and nitro guarantees (they use a magic value for `callTo` and also use `data`). 

We would like a format that does not treat any single use of the `data` field in a special way, and can cope with multiple future usages of that field that we don't even know about yet (but certainly the various virtual funding optimizations to nitro that we are considering). 

We can use some of the following tricks: 

- magic values
- custom coders (other than abi.encode -- e.g. abi.encodePacked or a custom bytes manipulator)
- self describing formats
- versioned coders.

Questions:
- do we need two fields, or can we use one field? Could the "data type" be indicated by the first couple of bytes of `data` itself?
- how will we deal with using the `data` field in multiple interesting ways at the same time?

> **[Defined] How will we solve it**
> A clear and concise description of what you want to happen, which can include implementation suggestions
> Include an estimate (~ 1point = 1day) 
> 
> **[Development]**
> [] This ticket has clearly outlined the expected outcome, and I can complete this ticket with no additional refinement 
> 
> 
> **Additional context** Add any other context or screenshots about the feature request here: notion doc, github discussion or ticket

**Comment by andrewgordstewart** [comment]
> Could the "data type" be indicated by the first couple of bytes of data itself?

What is the argument for using a "data type" at all?

**Comment by geoknee** [comment]
If the `data` (now known as `metadata`) field is to be used in multiple distinct ways, there needs to be some way to declare which way in the format itself. For example, sometimes the `metadata` will encode a guarantee. Other times, it might encode the address and calldata for a `WithdrawHelper`. It seems to me that a  "data type" is the easiest way to declare which decoder to use on the `metadata`. This is essentially making the `metadata` a discriminated union type, with the "data type" being the discriminant. This is a pattern we already use in our current outcome format:

https://github.com/statechannels/statechannels/blob/5ced1f55e25947e2b10576beb61f683a12e599d2/packages/nitro-protocol/contracts/Outcome.sol#L23-L24

Whether that data type is actually a separate field on the exit format is a secondary question (it can be absorbed into the `metadata` field). 

The only alternative I can think of is to have all of the anticipated uses of `metadata` "present" and decode-able in every outcome / exit. This is making `metadata` a product or intersection type. A downside is that this bloats the format with a lot of unused data (which grows as we add more and more uses for `metadata`). We would also need to have a way of switching the fields "off" -- say with a default or null value (like we currently do with the zero address). It's not clear to me that this will always be possible / straightforward.  Another thing to consider with this approach is forwards-compatibility. It's less clear that data encoded today will be decode correctly tomorrow when a newer decoder is expecting `metadata` to represent something different.

**Comment by geoknee** [comment]
Closing via #42
